#!/bin/bash
pdflatex photocathode
# bibtex photocathode
# pdflatex photocathode
# pdflatex photocathode
rm photocathode.toc
rm photocathode.log
rm photocathode.blg
rm photocathode.bbl
rm photocathode.aux
rm photocathode.out
