#!/bin/bash
lualatex photocathode
# bibtex photocathode
# lualatex photocathode
# lualatex photocathode
# rm photocathode.toc
# rm photocathode.log
# rm photocathode.blg
# rm photocathode.bbl
# rm photocathode.aux
# rm photocathode.out
